version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  ignore:
  - dependency-name: "@types/node"
    versions:
    - "> 12"
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: cspell
    versions:
    - 5.2.4
    - 5.3.0
    - 5.3.1
    - 5.3.10
    - 5.3.11
    - 5.3.2
    - 5.3.3
    - 5.3.4
    - 5.3.5
    - 5.3.6
    - 5.3.7
    - 5.3.8
    - 5.3.9
  - dependency-name: "@semantic-release/npm"
    versions:
    - 7.0.10
    - 7.1.0
  - dependency-name: nock
    versions:
    - 13.0.10
    - 13.0.6
    - 13.0.7
    - 13.0.8
    - 13.0.9
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  commit-message:
    prefix: chore
    include: scope
